AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Visitor Counter Dynamo Table
Resources:
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      PrimaryKey: 
        Name: id
        type: number
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        