version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "create-dynamodb-visitor"
s3_prefix = "create-dynamodb-visitor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
